apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::815668066821:role/eksctl-OleksandrHavron-cluster-addon-iamserv-Role2
    eks.amazonaws.com/sts-regional-endpoints: "true"
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  serviceAccountName: aws-load-balancer-controller
  containers:
        